version: "3.7"

services:
    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        environment:
            - POSTGRES_USER=docker
            - POSTGRE_PASSWORD=ignite
            - POSTGRES_DB=rentx
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/data/postgres
        network_mode: host
    app:
        build: .
        container_name: rentx
        volumes:
            - .:/usr/app
        network_mode: host

volumes:
    pgdata:
        driver: local
